// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PF2022_03_BlazorApp.DAL;

#nullable disable

namespace PF202203BlazorApp.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20221111182018_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("PF2022_03_BlazorApp.Models.Tikets", b =>
                {
                    b.Property<int>("tiketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("tiketId");

                    b.ToTable("tikets");
                });
#pragma warning restore 612, 618
        }
    }
}
